import type { Metadata } from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Layout} from "antd";
import {Content, Header} from "antd/es/layout/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="fr">
    <head>
        <title>Kanban app</title>
    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Layout>
          <Header>
              <h1 className={"text-amber-50"}>Kanban App</h1>
          </Header>

          <Content className={"p-10"}>
              {children}
          </Content>

      </Layout>
      </body>
    </html>
  );
}
